### ISSUE TITLE
Fix Youtube header content comparison

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/Automatic-Featured-Images-from-Videos#10]
https://wordpress.org/support/topic/need-to-update-for-404-for-youtube?replies=2#post-7749550

"Testing for HTTP/1.0 fails on Youtube. Youtube now returns HTTP/1.1.

In order to fix, change the beginning of line 59 from:

$video_thumbnail_url = $file_headers[0] !== 'HTTP/1.0 404 Not Found' ?

to:

$video_thumbnail_url = (strrpos($file_headers[0], '404 Not Found') === false) ?"

**Comment by jtsternberg** [comment]
@tw2113 you have commit access.

**Comment by tw2113** [comment]
I patched it in a branch, but it's good practice to use issues for tracking purposes anyway :)

Waiting on fix confirmation from the original reporter.

**Comment by jtsternberg** [comment]
Fair enough, but I just patched it to check both ways.
