### ISSUE TITLE
"_is_video" key is added to all posts?

### ISSUE THREAD

**Issue by crispinbixler** [WebDevStudios/Automatic-Featured-Images-from-Videos#11]
I'm noticing that the key "_is_video" is applied to all posts whether there's a video or not. 

This is affecting a conditional statement that we're using.

I'm sure I'm overlooking something but thought I'd ask. Should the value for the key be blank? I don't see a value associated with the _is_video key. 

Using a plugin called "Post Meta Inspector" I'm seeing this output for video and non-video posts:
Key              Value
_is_video      '' "

Thanks for any clues - let me know what other info you need. :)
Regarding this site: mofaul.com/blog

**Comment by tw2113** [comment]
It does indeed look like it is getting set on the post regardless.

	if ( ! $do_video_thumbnail ) {
		return update_post_meta( $post_id, '_is_video', false );
	}

However, it's also being set to boolean false when there is none found. Not sure the logic there at the time as I wasn't on the original team for this plugin. If you check for empty() or do a comparison to false, that should help at the moment with preventing doing anything when no value is available.

**Comment by tw2113** [comment]
It does indeed look like it is getting set on the post regardless.

	if ( ! $do_video_thumbnail ) {
		return update_post_meta( $post_id, '_is_video', false );
	}

However, it's also being set to boolean false when there is none found. Not sure the logic there at the time as I wasn't on the original team for this plugin. If you check for empty() or do a comparison to false, that should help at the moment with preventing doing anything when no value is available.

**Comment by crispinbixler** [comment]
Thanks for getting back to me so quickly and for the tip. :)

**Comment by tw2113** [comment]
Welcome. :)
