### ISSUE TITLE
Filter the content length to check for

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/Automatic-Featured-Images-from-Videos#17]
Defaults to 800 characters now, but would be nice to allow others to change as they see fit.

**Comment by tw2113** [comment]
Check 17-content-length-filter branch

**Comment by binarygary** [comment]
Fairly certain this can be closed.
https://github.com/WebDevStudios/Automatic-Featured-Images-from-Videos/blob/master/automatic-featured-images-from-videos.php#L63

**Comment by tw2113** [comment]
Sort of, I'd say #25 needs to be covered first, and then we could likely close both

**Comment by tw2113** [comment]
Closing in favor of #25, deleted branch.

**Comment by tw2113** [comment]
Going to re-open this one. I'm not presently a fan of making the user re-query for data just to provide a blob of content to hunt through.

**Comment by tw2113** [comment]
See 138f674
