### ISSUE TITLE
Should a metabox be displayed if a video is present with the video and other data?

### ISSUE THREAD

**Issue by binarygary** [WebDevStudios/Automatic-Featured-Images-from-Videos#28]
At the very least we could easily add a metabox containing the video?

If it's available, maybe the runtime?

**Comment by tw2113** [comment]
I see no real issue with this. Perhaps a side item towards the bottom. Indicate that it's collected info from Auto Featured Images for what we used for our processing.

**Comment by binarygary** [comment]
Work is in branch:
https://github.com/WebDevStudios/Automatic-Featured-Images-from-Videos/tree/feature/display_video_metabox_post_edit

**Comment by tw2113** [comment]
Stuck with the Video URL and the Video Embed URL. Closing for 1.1.0.

**Comment by tw2113** [comment]
Reopening for a moment because I noticed the text at https://github.com/WebDevStudios/Automatic-Featured-Images-from-Videos/blob/master/automatic-featured-images-from-videos.php#L377-L379 isn't i18n ready, and this issue is related to that output.

**Comment by binarygary** [comment]
Pushed fix in commit https://github.com/WebDevStudios/Automatic-Featured-Images-from-Videos/commit/165acebf5a7b5a414e9107efb933e8f9ed562136

**Comment by tw2113** [comment]
Closing as it's in the release110 branch
