### ISSUE TITLE
feature/bulk-update: continue working on the jQuery involved with bulk edit process buttons

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/Automatic-Featured-Images-from-Videos#31]
1. Move post type and i18n strings to wp_localize_script().
2. Move output to an external js file.

**Comment by binarygary** [comment]
Both points are handled in the most recent commit https://github.com/WebDevStudios/Automatic-Featured-Images-from-Videos/tree/feature/bulk-update

**Comment by tw2113** [comment]
Looking good overall. I can't find any lingering issues that need immediately addressed, other than perhaps some QA.

**Comment by binarygary** [comment]
QA would be great.
I've been testing as I go, but extra eyes in different environments would be great.
