### ISSUE TITLE
feature/display_video_metabox_post_edit: featured image not being set.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/Automatic-Featured-Images-from-Videos#32]
Iframe metabox is showing up like expected. Featured image not setting.

**Comment by binarygary** [comment]
Doh! Dumb error.  When I refactored this I missed passing the $post_id to the new function that saved the thumbnail.

Fixed in https://github.com/WebDevStudios/Automatic-Featured-Images-from-Videos/pull/34

**Comment by tw2113** [comment]
Confirmed working again.
