### ISSUE TITLE
feature/display_video_metabox_post_edit: metabox content

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/Automatic-Featured-Images-from-Videos#33]
Not sure how I feel about re-embedding the video again. It's already going to be embedded in the visual editor, fully playable.

Perhaps instead of an iframe, we simply list the video URL that was found.

**Comment by binarygary** [comment]
I'm fine with this.
I see the logic in both.

Addressed in https://github.com/WebDevStudios/Automatic-Featured-Images-from-Videos/pull/34 despite the branch name, it now displays the URL and embed URL in the meta box.

**Comment by tw2113** [comment]
Closing as merged into master.
