### ISSUE TITLE
Use of get_the_ID() when $post_id is passed in

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/Automatic-Featured-Images-from-Videos#4]
Nitpicky extra function call but we do get the specific post ID passed into the callback that we can use instead of get_the_ID().

**Comment by bradp** [comment]
We changed this in 3a7ff90f711a891640dca38541821a28c7a69fb8, as we found it to be more consistent, because otherwise we seemed to get revision IDs or something sometime. 

Brad Parbs

**Comment by tw2113** [comment]
Ah.

```
if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
	return;
}
```
should solve that issue, for future consideration. The save_posttype hook would have those two firing regularly.

**Comment by bradp** [comment]
PR it up!

Brad Parbs

**Comment by jtsternberg** [comment]
:+1:

**Comment by tw2113** [comment]
This got fixed at some point.
