### ISSUE TITLE
LiveLeak support

### ISSUE THREAD

**Issue by Hyngwar** [WebDevStudios/Automatic-Featured-Images-from-Videos#42]
Hi,

Great plugin, could you guys look into support for LiveLeak as well? Having automatic featured images for LiveLeak videos would be a nice addition.

Greetings.

**Comment by tw2113** [comment]
One of the biggest key factors is going to be if their API has any endpoints or urls that return images of the videos. For example, with YouTube, there is `https://img.youtube.com/vi/3M_Gg1xAHE4/hqdefault.jpg` The `3M_Gg1xAHE4` portion is the video ID and we're able to drop that in the middle of the URL before sideloading into the media library. We don't create the images, we just grab from the video site :D

**Comment by tw2113** [comment]
Tacking this onto this ticket: seeing a request for support of dailymotion.com as well.

**Comment by Hyngwar** [comment]
I hope it's possible, I do find large images of the first frame of videos in the source code though. Whatever that means :-).

**Comment by tw2113** [comment]
I am not managing to find any inkling of an API to retrieve data from at the present moment. If someone can show me where it's at, I'm happy to re-open, but for now I am having to close.
