### ISSUE TITLE
Gutenberg compatibility

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/Automatic-Featured-Images-from-Videos#51]

**Comment by binarygary** [comment]
I did not test this super-thoroughly. 
I did verify that on saving the content containing the URL still passed the youtube regex and a featured image was added.

The only note I have is that the content we will be looking at could be quite a bit longer than the default 800 characters we look at initially.

**Comment by tw2113** [comment]
Did the "which block" matter? or does it all come in as part of $post->post_content upon save, regardless of how many blocks got added to the page? May be a "Michael doesn't know how Gutenberg internally works and where it saves" case, for what it's worth.

Quick idea: filter callback that checks if Gutenberg is active, and returns a much higher character count to slice off if it is.

**Comment by tw2113** [comment]
Let's do a bit more testing/confirmation with this one, but I feel we have majority of what we need.

**Comment by tw2113** [comment]
Sort of undoing, because I'm now just defaulting to 4000 characters.

See 1548826
