### ISSUE TITLE
Way to trigger setting of featured image, in mass, for existing posts.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/Automatic-Featured-Images-from-Videos#7]
https://wordpress.org/support/topic/way-to-mass-update-existing-posts?replies=4

**Comment by Caf** [comment]
Since the only other plugin doing that is broken atm, that would be an AWESOME addition.  ;)

**Comment by tw2113** [comment]
After some quick testing, I found that a WP_Query as simple as this would do the trick:
```
$args = array(
	'post_type' => array( 'post' ),
	'posts_per_page' => -1,
	'cache_results'  => false,
	'update_post_meta_cache' => false,
);
$query = new WP_Query( $args ); var_dump($query);
foreach( $query->posts as $post ) {
	wds_set_media_as_featured_image( $post->ID, $post );
}
```

**Comment by renatonascalves** [comment]
`'posts_per_page' => -1,` will overload and crash the server.

**Comment by tw2113** [comment]
Would be easy enough to amend and utilize the offset parameter.

**Comment by tw2113** [comment]
Closing in favor of #27
