### ISSUE TITLE
Add support for cookie-less YouTube video urls

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/Automatic-Featured-Images-from-Videos#8]
Hi,

Could you consider implementing support for the URLs for YouTube's privacy mode? This is a mode that lets you embed videos without YouTube setting cookies on your visitor's PC until after the visitor starts playing the video.

If the regular YouTube link looks like:

https://www.youtube.com/watch?v=CAMWdvo71ls

and the embed version looks like:

https://www.youtube.com/embed/CAMWdvo71ls

the privacy embed version looks like:

https://www.youtube-nocookie.com/embed/CAMWdvo71ls

As you can see, all that changes if you switch from regular embed to privacy embed is the domain name: youtube.com becomes youtube-nocookie.com.

(Without having tested this) I suggest you change the regular expression testing for YouTube links as follows: youtube.com becomes youtube(-nocookie)?.com

You can try this out for yourself: 1) go to YouTube; 2) select a video; 3) Click Share; 4) Click Embed; 5) Click Show More; 6) Select "Enable privacy-enhanced mode"; and 7) copy the embed code.

https://wordpress.org/support/topic/support-cookieless-youtube-urls?replies=1#post-7499086

**Comment by tw2113** [comment]
This regex should cover the extra domain portion:

`\/\/(www\.)?(youtu|youtube|youtube-nocookie)\.(com|be)\/(watch|embed)?\/?(\?v=)?([a-zA-Z0-9\-\_]+)`

**Comment by tw2113** [comment]
See 8-cookiemonster-sad

**Comment by tw2113** [comment]
Merged into alpha, which is being used for what will be 1.1.0

**Comment by tw2113** [comment]
Re-opening because I believe we started using master for 1.1.0 and this isn't in master at all.

**Comment by tw2113** [comment]
Brought back in 5710546 and release110 branch

**Comment by Christian-CFP** [comment]
So what is the code (I guess for the .htaccess) to enter?

This? `\/\/(www\.)?(youtu|youtube|youtube-nocookie)\.(com|be)\/(watch|embed)?\/?(\?v=)?([a-zA-Z0-9\-\_]+)`

**Comment by tw2113** [comment]
Nothing that you need to add to htaccess. This is all already built into the plugin, and nothing you need to add yourself.
