### ISSUE TITLE
Update on the way? Plugin not working. 

### ISSUE THREAD

**Issue by tylerregas** [WebDevStudios/Automatic-Featured-Images-from-Videos#9]
I know your team is super busy, but if at all possible, it would be really nice to get an update to this awesome plugin. Thanks a bunch, and nice work out there!! -TC

**Comment by tw2113** [comment]
We're going to need more info than "Plugin not working" as we haven't had anyone else claim it's not working recently.

For instance, what URL are you trying to use with it? Because the regex in the plugin is set to only match a certain format at the moment.
